version: 2.1
orbs:
  node: circleci/node@5.0.2
  eb: circleci/aws-elastic-beanstalk@2.0.1
  aws-cli: circleci/aws-cli@1.3.1
jobs:
  build:
    docker:
      - image: "cimg/base:stable"
      #installing and setting up node/AWS/eb
    steps:
      - node/install
      - checkout
      - aws-cli/setup
      - checkout
      - eb/setup
      # installing Front End dependancies 
      - run:
          name: Front-End Install
          command: |
            npm run frontend:install
      # installing Back End dependancies
      - run:
          name: Back-End Install
          command: |
            npm run api:install
      # Building Front End
      - run:
          name: Front-End Build
          command: |
            npm run frontend:build
      # Building Back End
      - run:
          name: Back-End Build
          command: |
            npm run api:build
      # Deploying Front End
      - run:
          name: Deploy App
          command: |
            npm run frontend:deploy
      # Deploying Back End
      - run:
          name: Deploy api
          command: |
            npm run api:deploy
workflows:
    jobs:
      - build:
          filters:
            branches:
              only:
                - master
          type: approval
          requires:
            - build
